django_app/urls.py
from django.urls import path
from django_app import views


app_name = "django_app"
urlpatterns = [
    path("index/", views.index, name="index"),
    path("", views.Home.as_view(), name=""),
    path("home/", views.Home.as_view(), name="home"),

    path("user/register/", views.register, name="register"),
    path("user/login/", views.login_f, name="login"),
    path("user/logout/", views.logout_f, name="logout"),

    path("post/create/", views.create, name="create"),
    path("post/<int:post_id>/detail/", views.read, name="read"),
    path("post/list/", views.read_list, name="read_list"),
    path("post/<int:post_id>/update/", views.update, name="update"),
    path("post/<int:post_id>/delete/", views.delete, name="delete"),
]

django_settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('django_app.urls')),

    re_path(r'^.*$', lambda request: redirect('django_app:', permanent=False), name='redirect'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.utils import timezone

# Create your models here.


class PostModel(models.Model):
    """
    Модель Поста
    """
    author = models.ForeignKey(
        editable=True,
        blank=True,
        null=True,
        default=None,
        verbose_name='Автор',
        help_text='<small class="text-muted">ForeignKey</small><hr><br>',

        to=User,
        on_delete=models.CASCADE,
    )

    title = models.CharField(
        validators=[MinLengthValidator(0), MaxLengthValidator(300), ],
        unique=True,
        editable=True,
        blank=True,
        null=True,
        default='',
        verbose_name='Заголовок',
        help_text='<small class="text-muted">CharField [0, 300]</small><hr><br>',

        max_length=300,
    )
    description = models.TextField(
        validators=[MinLengthValidator(0), MaxLengthValidator(3000), ],
        editable=True,
        blank=True,
        null=True,
        default="",
        verbose_name='Описание',
        help_text='<small class="text-muted">TextField [0, 3000]</small><hr><br>',

        max_length=3000,
    )
    is_completed = models.BooleanField(
        editable=True,
        blank=True,
        null=False,
        default=False,
        verbose_name='Статус выполнения',
        help_text='<small class="text-muted">BooleanField</small><hr><br>',
    )
    created = models.DateTimeField(
        editable=True,
        blank=True,
        null=True,
        default=timezone.now,
        verbose_name='Дата и время создания',
        help_text='<small class="text-muted">DateTimeField</small><hr><br>',

        auto_now=False,
        auto_now_add=False,
    )
    updated = models.DateTimeField(
        editable=True,
        blank=True,
        null=True,
        default=timezone.now,
        verbose_name='Дата и время обновления',
        help_text='<small class="text-muted">DateTimeField</small><hr><br>',

        auto_now=False,
        auto_now_add=False,
    )

    class Meta:
        app_label = 'django_app'
        ordering = ('-updated', 'title')
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        db_table = 'django_app_post_model_table'

    def __str__(self):
        if self.is_completed:
            completed = "Активно"
        else:
            completed = "Неактивно"
        return f"{self.title}({self.id}) | {self.description[0:30]}... | {completed} | {self.updated}"

django_app/views.py
import time

from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.core.cache import caches
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from django.utils import timezone
from django.views import View

from django_app import models as django_models, utils as django_utils

# Create your views here.

DatabaseCache = caches["default"]
LocMemCache = caches["ram_cache"]


@django_utils.logging_txt_decorator
def index(request):
    return HttpResponse("<h1>This is a Index Page</h1>")


@django_utils.logging_txt_decorator
def index_json(request):
    return JsonResponse(data={"response": "This is a Index Page"}, safe=False)


class Home(View):
    @django_utils.logging_txt_decorator
    def get(self, request, *args, **kwargs):
        context = {}

        return render(request, "django_app/home.html", context)


@django_utils.logging_txt_decorator
def register(request):
    if request.method == "POST":
        username = request.POST.get('username', None)
        password = request.POST.get('password', "")
        password2 = request.POST.get('password2', "")

        if password and password != password2:
            raise Exception("пароли не совпадают!")
        if username and password:
            User.objects.create(
                username=username,
                password=make_password(password),
            )
            time.sleep(1)

            return redirect(reverse('django_app:login', args=()))
        else:
            raise Exception("данные не заполнены!")
    context = {}

    return render(request, "django_app/user_register.html", context)


@django_utils.logging_txt_decorator
def login_f(request):
    if request.method == "POST":
        time.sleep(1)

        username = request.POST.get('username', "").strip()
        password = request.POST.get('password', "").strip()
        if username and password:
            user_obj = authenticate(username=username, password=password)
            login(request, user_obj)

            return redirect(reverse('django_app:', args=()))
        else:
            raise Exception("данные не совпадают!")
    context = {}

    return render(request, "django_app/user_login.html", context)


@django_utils.logging_txt_decorator
@django_utils.login_required_decorator
def logout_f(request):
    logout(request)
    return redirect(reverse("django_app:login", args=()))


@django_utils.logging_txt_decorator
@django_utils.login_required_decorator
def create(request):
    if request.method == "POST":
        title = request.POST.get("title", "")
        description = request.POST.get("description", "")

        django_models.PostModel.objects.create(
            author=request.user,
            title=title,
            description=description,
            is_completed=False,
        )

        time.sleep(1)
        return redirect(reverse("django_app:read_list", args=()))
    context = {}

    return render(request, "django_app/post_create.html", context)


@django_utils.logging_txt_decorator
@django_utils.login_required_decorator
def read(request, post_id=None):
    post = django_utils.caching(
        LocMemCache, f"read django_models.PostModel.objects.get(id={post_id})", 1,
        lambda: django_models.PostModel.objects.get(id=post_id)
    )

    context = {"post": post}

    return render(request, "django_app/post_detail.html", context)


@django_utils.logging_txt_decorator
@django_utils.login_required_decorator
def read_list(request):
    post_list = django_utils.caching(
        LocMemCache, f"read_list django_models.PostModel.objects.all()", 1,
        lambda: django_models.PostModel.objects.all()
    )

    is_detail_view = request.GET.get("is_detail_view", True)
    if is_detail_view == "False":
        is_detail_view = False
    elif is_detail_view == "True":
        is_detail_view = True

    page = django_utils.paginate(request=request, objects=post_list, num_page=4)
    context = {
        "page": page,
        "is_detail_view": is_detail_view
    }

    return render(request, "django_app/post_list.html", context)


@django_utils.logging_txt_decorator
@django_utils.login_required_decorator
def update(request, post_id=None):
    if request.method == "POST":
        post = django_models.PostModel.objects.get(id=post_id)
        is_completed = request.POST.get("is_completed", "")
        title = request.POST.get("title", "")
        description = request.POST.get("description", "")
        if is_completed:
            if is_completed == "False":
                post.is_completed = False
            elif is_completed == "True":
                post.is_completed = True
        if title and title != post.title:
            post.title = title
        if description and description != post.description:
            post.description = description
        post.updated = timezone.now()
        post.save()

        time.sleep(1)
        return redirect(reverse("django_app:read_list", args=()))
    post = django_models.PostModel.objects.get(id=post_id)
    context = {
        "post": post
    }

    return render(request, "django_app/post_change.html", context)


@django_utils.logging_txt_decorator
@django_utils.login_required_decorator
def delete(request, post_id=None):

    django_models.PostModel.objects.get(id=post_id).delete()

    time.sleep(1)
    return redirect(reverse("django_app:read_list", args=()))

templates/django_app/post_change.html
{% extends "components/base.html" %}
{% load django_app_extras %}
{% load static %}


{% block title %}
    {% text_upper_case text='изменение поста' %}
{% endblock title %}

{% block header %}
    изменение поста
{% endblock header %}

{% block description %}
    эта страница содержит форму, которая позволяет обновить уже существующий пост
{% endblock description %}

{% block main %}
<div class="container shadow-lg m-0 p-0">
    <div class="shadow border-bottom">
        <div class="d-flex text-start">
            <a class="text-decoration-none lead btn btn-sm btn-outline-primary m-1 p-2" href="{% url 'django_app:read_list' %}">
                <= список всех постов <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">{{ post_count }}</i>
            </a>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-1 row-cols-lg-1 custom-background-transparent-middle m-0 p-0">
        <form action="{% url 'django_app:update' post.id %}"
                  method="POST"
                  target="_self"
                  enctype="multipart/form-data"
                  name="idea_create"
                  autocomplete="on"
                  class="text-center"
        >
            {% csrf_token %}
            <div>
                <div>
                    <label class="form-control-sm w-50 m-1">
                        Заголовок:
                        <input type="text"
                               name="title"
                               required=""
                               placeholder="вводить 'заголовок' здесь..."
                               value="{{ post.title }}"
                               minlength="1"
                               maxlength="300"
                               class="form-control form-control-sm"
                        />
                        <small class="text-muted">количество символов: <= 300</small>
                    </label>
                    <label class="form-control-sm w-75 m-1">
                        Описание:
                        <textarea type="text"
                                  name="description"
                                  required=""
                                  placeholder="вводить 'описание' здесь..."
                                  minlength="1"
                                  maxlength="3000"
                                  rows="3"
                                  class="form-control form-control-sm"
                        >{{ post.description }}</textarea>
                        <small class="text-muted">количество символов: <= 3000</small>
                    </label>
                </div>
            </div>
            <hr/>
            <div class="container-fluid text-center">
                <ul class="row row-cols-auto row-cols-md-auto row-cols-lg-auto nav justify-content-center">
                    <li class="m-1">
                        <button class="btn btn-lg btn-outline-primary" type="submit">отправить</button>
                    </li>
                    <li class="m-1">
                        <button class="btn btn-lg btn-outline-warning" type="reset">сбросить</button>
                    </li>
                </ul>
            </div>
        </form>
    </div>
</div>
{% endblock main %}

templates/django_app/post_create.html
{% extends "components/base.html" %}
{% load django_app_extras %}
{% load static %}


{% block title %}
    {% text_upper_case text='создание поста' %}
{% endblock title %}

{% block header %}
    создание поста
{% endblock header %}

{% block description %}
    эта страница содержит форму, которая позволяет добавить новый пост
{% endblock description %}

{% block main %}
<div class="container shadow-lg m-0 p-0">
    <div class="shadow border-bottom">
        <div class="d-flex text-start">
            <a class="text-decoration-none lead btn btn-sm btn-outline-primary m-1 p-2" href="{% url 'django_app:read_list' %}">
                <= список всех постов <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">{{ post_count }}</i>
            </a>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-1 row-cols-lg-1 custom-background-transparent-middle m-0 p-0">
        <form action="{% url 'django_app:create' %}"
                  method="POST"
                  target="_self"
                  enctype="multipart/form-data"
                  name="idea_create"
                  autocomplete="on"
                  class="text-center"
        >
            {% csrf_token %}
            <div>
                <div>
                    <label class="form-control-sm w-50 m-1">
                        Заголовок:
                        <input type="text"
                               name="title"
                               required=""
                               placeholder="вводить 'заголовок' здесь..."
                               value=""
                               minlength="1"
                               maxlength="300"
                               class="form-control form-control-sm"
                        />
                        <small class="text-muted">количество символов: <= 300</small>
                    </label>
                    <label class="form-control-sm w-75 m-1">
                        Описание:
                        <textarea type="text"
                                  name="description"
                                  required=""
                                  placeholder="вводить 'описание' здесь..."
                                  minlength="1"
                                  maxlength="3000"
                                  rows="3"
                                  class="form-control form-control-sm"
                        ></textarea>
                        <small class="text-muted">количество символов: <= 3000</small>
                    </label>
                </div>
            </div>
            <hr/>
            <div class="container-fluid text-center">
                <ul class="row row-cols-auto row-cols-md-auto row-cols-lg-auto nav justify-content-center">
                    <li class="m-1">
                        <button class="btn btn-lg btn-outline-primary" type="submit">отправить</button>
                    </li>
                    <li class="m-1">
                        <button class="btn btn-lg btn-outline-warning" type="reset">сбросить</button>
                    </li>
                </ul>
            </div>
        </form>
    </div>
</div>
{% endblock main %}

templates/django_app/post_detail.html
{% extends "components/base.html" %}
{% load django_app_extras %}
{% load static %}


{% block title %}
    {% text_upper_case text='детальный просмотр' %}
{% endblock title %}

{% block header %}
    детальный просмотр
{% endblock header %}

{% block description %}
    эта страница содержит детальную информацию о существующем посте
{% endblock description %}

{% block main %}
<div class="container shadow-lg m-0 p-0">
    <div class="shadow border-bottom m-0 p-0">
        <div class="d-flex justify-content-around">
            <a class="text-decoration-none lead btn btn-sm btn-outline-primary m-1 p-2" href="{% url 'django_app:read_list' %}">
                <= список всех постов <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">{{ post_count }}</i>
            </a>
            <a class="text-decoration-none btn btn-sm btn-outline-success m-1 p-2" href="{% url 'django_app:create' %}">
                <i class="fa-solid fa-circle-plus m-0 p-1"></i>
                создать новый пост
            </a>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-1 row-cols-lg-1">
        <div class="col">
            <div class="card custom-background-transparent-middle">
                <div class="card-header">
                    <div class="m-0 p-3">
                        <div class="d-flex justify-content-around">
                            <h5>{{post.title}}</h5>
                            <form action="{% url 'django_app:update' post.id %}"
                                  method="POST"
                                  target="_self"
                                  enctype="multipart/form-data"
                                  name="idea_create"
                                  autocomplete="on"
                                  class="m-0 p-0"
                            >
                                {% csrf_token %}
                                <div>
                                    <input type="hidden"
                                       name="is_completed"
                                       required=""
                                       placeholder=""
                                       {% if post.is_completed %}
                                            value="False"
                                       {% else %}
                                            value="True"
                                       {% endif %}
                                       minlength="1"
                                       maxlength="32"
                                       class="form-control form-control-lg"
                                />
                                </div>
                                <div class="btn-group m-0 p-1">
                                    {% if post.is_completed %}
                                        <button class="btn btn-sm btn-outline-danger m-0 p-1" type="submit">
                                            <i class="fa-solid fa-circle-xmark text-danger m-0 p-1"></i>
                                            не выполнено
                                        </button>
                                    {% else %}
                                        <button class="btn btn-sm btn-outline-success m-0 p-1" type="submit">
                                            <i class="fa-solid fa-circle-check text-success m-0 p-1"></i>
                                            выполнено
                                        </button>
                                    {% endif %}
                                    <a href="{% url 'django_app:update' post.id %}" class="btn btn-sm btn-outline-warning m-0 p-1">
                                        <i class="fa-solid fa-screwdriver-wrench text-warning m-0 p-1"></i>
                                        изменить
                                    </a>
                                    <a href="{% url 'django_app:delete' post.id %}" class="btn btn-sm btn-outline-danger m-0 p-1">
                                        <i class="fa-solid fa-circle-minus text-danger m-0 p-1"></i>
                                        удалить
                                    </a>
                                </div>
                            </form>
                        </div>
                        {% if post.is_completed %}
                            <div class="feature-icon bg-success bg-gradient text-white">
                                <p class="m-0 p-1"></p>
                            </div>
                        {% else %}
                            <div class="feature-icon bg-danger bg-gradient text-white">
                                <p class="m-0 p-1"></p>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="card-body">
                    <p class="m-0 p-3">{{ post.description }}</p>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-between m-0 p-1">
                        <small class="text-warning">
                            {{ post.created }} [создано]
                        </small>
                        <small class="text-success">
                            {{ post.updated }} [обновлено]
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

{% block footer %}
    {% include 'components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}

templates/django_app/post_list.html
{% extends "components/base.html" %}
{% load django_app_extras %}
{% load static %}


{% block title %}
    {% text_upper_case text='список постов' %}
{% endblock title %}

{% block header %}
    список постов
{% endblock header %}

{% block description %}
    на этой странице отображены все посты
{% endblock description %}

{% block main %}
<div class="container shadow-lg custom-background-transparent-hard m-0 p-0">
    <div class="shadow border-bottom m-0 p-0">
        <div class="d-flex justify-content-around">
            <h6 class="lead fw-bold m-1 p-2">количество постов <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">{{ post_count }}</i>:</h6>
            <a class="text-decoration-none btn btn-sm btn-outline-success m-1 p-2" href="{% url 'django_app:create' %}">
                <i class="fa-solid fa-circle-plus m-0 p-1"></i>
                создать новый пост
            </a>
        </div>
    </div>
    <div class="text-end">
        <form action="{% url 'django_app:read_list' %}"
        method="GET"
        target="_self"
        enctype="multipart/form-data"
        name="idea_create"
        autocomplete="on"
        class="m-0 p-0"
        >
        {% csrf_token %}
        <div>
        <input type="hidden"
           name="is_detail_view"
           required=""
           placeholder=""
           {% if is_detail_view %}
                value="False"
           {% else %}
                value="True"
           {% endif %}
           minlength="1"
           maxlength="32"
           class="form-control form-control-sm"
        />
        </div>
        {% if is_detail_view %}
            <button class="btn btn-lg btn-light m-0 p-1" type="submit">
                <i class="fa-solid fa-list-check text-secondary m-0 p-1"></i>
                вид списком
            </button>
        {% else %}
            <button class="btn btn-lg btn-light m-0 p-1" type="submit">
                <i class="fa-solid fa-calendar-week text-secondary m-0 p-"></i>
                детальный вид
            </button>
        {% endif %}
        </form>
    </div>

    {% if page %}
        <div class="container d-flex justify-content-center align-self-center">
            {% include 'components/paginator.html' %}
        </div>

        {% if is_detail_view %}
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
                {% for post in page %}
                    <div class="col">
                        <div class="card border border-1 border-dark custom-background-transparent-middle m-1 p-0">
                            <div class="card-header">
                                <div class="m-0 p-3">
                                    <div class="d-flex justify-content-around">
                                        <a class="text-decoration-none text-dark" href="{% url 'django_app:read' post.id %}">
                                            <h5>{{ post.title|cut_string:30 }} [{{ post.author.username }}]</h5>
                                        </a>
                                        <form action="{% url 'django_app:update' post.id %}"
                                              method="POST"
                                              target="_self"
                                              enctype="multipart/form-data"
                                              name="idea_create"
                                              autocomplete="on"
                                              class="m-0 p-0"
                                        >
                                            {% csrf_token %}
                                            <div>
                                                <input type="hidden"
                                                   name="is_completed"
                                                   required=""
                                                   placeholder=""
                                                   {% if post.is_completed %}
                                                        value="False"
                                                   {% else %}
                                                        value="True"
                                                   {% endif %}
                                                   minlength="1"
                                                   maxlength="32"
                                                   class="form-control form-control-sm"
                                            />
                                            </div>
                                            <div class="btn-group m-0 p-1">
                                                {% if post.is_completed %}
                                                    <button class="btn btn-sm btn-outline-danger m-0 p-1" type="submit">
                                                        <i class="fa-solid fa-circle-xmark text-danger m-0 p-1"></i>
                                                        не выполнено
                                                    </button>
                                                {% else %}
                                                    <button class="btn btn-sm btn-outline-success m-0 p-1" type="submit">
                                                        <i class="fa-solid fa-circle-check text-success m-0 p-1"></i>
                                                        выполнено
                                                    </button>
                                                {% endif %}
                                                <a href="{% url 'django_app:delete' post.id %}" class="btn btn-sm btn-outline-danger m-0 p-1">
                                                    <i class="fa-solid fa-circle-minus text-danger m-0 p-1"></i>
                                                    удалить
                                                </a>
                                            </div>
                                        </form>
                                    </div>
                                    {% if post.is_completed %}
                                        <div class="feature-icon bg-success bg-gradient text-white">
                                            <p class="m-0 p-1"></p>
                                        </div>
                                    {% else %}
                                        <div class="feature-icon bg-danger bg-gradient text-white">
                                            <p class="m-0 p-1"></p>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="card-body">
                                <p class="m-0 p-3">{{ post.description|cut_string:100 }}</p>
                            </div>
                            <div class="card-footer">
                                <div class="d-flex justify-content-between m-0 p-1">
                                    <small class="text-warning m-1 p-0">
                                        {{ post.created }} [создано]
                                    </small>
                                    <small class="text-success m-1 p-0">
                                        {{ post.updated }} [обновлено]
                                    </small>
                                </div>
                                <a class="text-decoration-none text-dark" href="{% url 'django_app:read' post.id %}">
                                    <button class="btn btn-sm btn-outline-primary w-100 m-0 p-1" type="submit">
                                        <i class="fa-solid fa-circle-info m-0 p-1"></i>
                                        подробнее
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="m-0 p-1">
                <ul class="m-0">
                    {% for post in page %}
                        <li class="text-start m-0 p-0 border border-1 border-dark p-1">
                            {% if post.is_completed %}
                                <div class="feature-icon bg-success d-flex justify-content-between">
                            {% else %}
                                <div class="feature-icon bg-danger d-flex justify-content-between">
                            {% endif %}
                                <a class="text-decoration-none text-white small w-50" href="{% url 'django_app:read' post.id %}">
                                    <div class="d-flex">
                                        <h6 class="lead m-1 p-1">{{ post.description|cut_string:20 }}</h6>
                                        <small class="m-0 p-2">{{ post.description|cut_string:30 }}</small>
                                    </div>
                                </a>
                                <div class="m-1 p-1">
                                    <small class="text-white m-1 p-0">
                                        {{ post.updated }} [обновлено]
                                    </small>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <div class="container d-flex justify-content-center align-self-center">
            {% include 'components/paginator.html' %}
        </div>
    {% else %}
        {% include 'components/aborted.html' %}
    {% endif %}
</div>
{% endblock main %}