django_app/urls.py
from django.urls import path
from django_app import views


app_name = "django_app"
urlpatterns = [
    path("index/", views.index, name="index"),
    path("", views.Home.as_view(), name=""),
    path("home/", views.Home.as_view(), name="home"),

    path("user/register/", views.register, name="register"),
    path("user/login/", views.login_f, name="login"),
    path("user/logout/", views.logout_f, name="logout"),

    path("post/create/", views.create, name="create"),
    path("post/<int:post_id>/detail/", views.read, name="read"),
    path("post/list/", views.read_list, name="read_list"),
    path("post/<int:post_id>/update/", views.update, name="update"),
    path("post/<int:post_id>/delete/", views.delete, name="delete"),
]

django_settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('django_app.urls')),

    re_path(r'^.*$', lambda request: redirect('django_app:', permanent=False), name='redirect'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/components/aborted.html
<hr/>
<div class="container">
    <div class="container-fluid">
        <p class="lead text-center text-danger">Данных нет!</p>
    </div>
</div>
<hr/>

templates/components/base.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="description" content="just for fun">
    <meta name="author" content="Bogdan">
    <meta name="generator" content="Custom">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}TWITTER 2.0{% endblock title %}
    </title>
    <link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">
    {#<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">#}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-5.0.2/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-free-6.3.0/css/all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font_zen/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
</head>
<body class="d-flex flex-column h-100 custom_body_1" style="min-height: 100vh;">
    {% include 'components/navbar.html' %}
    <main class="flex-shrink-0">
        <div class="container-fluid">
            <div class="container">
                <div class="container-fluid">
                    <div class="text-center">
                        <h1 class="display-5 fw-bold fst-italic">{% block header %}{% endblock header %}</h1>
                        <div class="col-lg-6 mx-auto">
                            <p class="lead mb-4">{% block description %}{% endblock description %}</p>
                        </div>
                    </div>
                </div>
            </div>
            <main class="container p-0 custom_main_1">
                {% block main %}{% endblock main %}
            </main>
        </div>
    </main>
    {% include 'components/footer.html' %}
    <script src="{% static 'js/bootstrap-5.0.2/bootstrap.min.js' %}"></script>
</body>
</html>

templates/components/footer.html
<footer class="container-fluid mt-auto footer page-footer custom-background-transparent-middle-hard">
    <ul class="row row-cols-auto row-cols-md-auto row-cols-lg-auto nav justify-content-center">
        <li class="m-1 p-1">
            <div class="navbar">
                <a class="btn btn-sm btn-outline-secondary" href="#">наверх</a>
            </div>
        </li>
        <li class="m-1 p-1">
            <div class="navbar dropup">
                <a class="dropdown-toggle btn btn-sm  btn-outline-danger" role="button" data-bs-toggle="dropdown">помощь!</a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <strong class="dropdown-header">мобильный телефон</strong>
                            <a class="dropdown-item disabled" href="#">+7 747 261 03 59</a>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <strong class="dropdown-header">почта (google)</strong>
                        <a class="dropdown-item disabled" href="#">bogdandrienko@gmail.com</a>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
</footer>

templates/components/navbar.html
{% load django_app_extras %}

<nav class="container-fluid navbar navbar-expand-lg navbar-light custom-background-transparent-middle-hard">
    <a class="navbar-brand" href="{% url 'django_app:' %}">Главная страница</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav navbar-collapse collapse" id="navbarSupportedContent">
        <li class="dropend">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                Профиль
                <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">аккаунт:
                    {% if user.is_authenticated %}
                        {{ user.username }}
                    {% else %}
                        аноним
                    {% endif %}
                </i>
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
                <li>
                    <strong class="dropdown-header">Профили пользователей</strong>
                    {% if user.is_authenticated %}
                        <a class="dropdown-item text-danger" href="{% url 'django_app:logout' %}">
                            <i class="fa-solid fa-list m-0 p-1"></i>
                            выйти из аккаунта
                        </a>
                    {% else %}
                        <a class="dropdown-item text-warning" href="{% url 'django_app:register' %}">
                            <i class="fa-solid fa-circle-plus m-0 p-1"></i>
                            регистрация новых пользователей
                            <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">пользователей: {{ user_count }}</i>
                        </a>
                        <a class="dropdown-item text-primary" href="{% url 'django_app:login' %}">
                            <i class="fa-solid fa-list m-0 p-1"></i>
                            войти в аккаунт
                        </a>
                    {% endif %}

                </li>
            </ul>
        </li>
        {% if user.is_authenticated %}
            <li class="dropend">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                    Публикация постов
                    <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">постов: {{ post_count }}</i>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <strong class="dropdown-header">Публикация постов</strong>
                        <a class="dropdown-item" href="{% url 'django_app:create' %}">
                            <i class="fa-solid fa-circle-plus m-0 p-1"></i>
                            создать новый пост
                        </a>
                        <a class="dropdown-item" href="{% url 'django_app:read_list' %}">
                            <i class="fa-solid fa-list m-0 p-1"></i>
                            список постов
                            <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">{{ post_count }}</i>
                        </a>
                    </li>
                </ul>
            </li>
        {% endif %}
    </ul>
</nav>

templates/components/paginator.html
<div class="pagination m-3 bd-example">
    <ul class="pagination">

        {% if page.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        {% if page.number != 1 %}
            <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
        {% endif %}

        {% if page.paginator.num_pages > 1 %}
            <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a></li>
        {% endif %}

        {% if page.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page.next_page_number }}" aria-label="next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}

    </ul>
</div>